//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t __libc_csu_fini(void);
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3);
int64_t _fini(void);
int64_t _GLOBAL__sub_I_main(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4);
int64_t _Z41__static_initialization_and_destruction_0ii(int32_t a1, int32_t a2);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
int32_t function_8b0(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle);
int64_t function_8c0(int64_t * a1, char * a2);
int64_t function_8d0(void);
int64_t function_8e0(int32_t a1);
void function_8f0(int64_t * d);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 2560; // 0x200d80
int64_t g2 = 2496; // 0x200d90
int64_t g3 = 0; // 0x200fd0
int64_t g4; // 0x201008
int32_t g5 = 0; // 0x201020
char g6 = 0; // 0x201130
int64_t g7; // 0x201131
int32_t g8;

// ------------------------ Functions -------------------------

// Address range: 0x888 - 0x89f
int64_t _init(void) {
    int64_t result = 0; // 0x896
    if (*(int64_t *)0x200fe8 != 0) {
        // 0x898
        __gmon_start__();
        result = &g8;
    }
    // 0x89a
    return result;
}

// Address range: 0x8b0 - 0x8b6
int32_t function_8b0(void (*func)(int64_t *), int64_t * arg, int64_t * dso_handle) {
    // 0x8b0
    return __cxa_atexit(func, arg, dso_handle);
}

// Address range: 0x8c0 - 0x8c6
int64_t function_8c0(int64_t * a1, char * a2) {
    // 0x8c0
    return _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(a1, a2);
}

// Address range: 0x8d0 - 0x8d6
int64_t function_8d0(void) {
    // 0x8d0
    return _ZNSt8ios_base4InitC1Ev();
}

// Address range: 0x8e0 - 0x8e6
int64_t function_8e0(int32_t a1) {
    // 0x8e0
    return _ZNSolsEi(a1);
}

// Address range: 0x8f0 - 0x8f6
void function_8f0(int64_t * d) {
    // 0x8f0
    __cxa_finalize(d);
}

// Address range: 0x900 - 0x92b
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    // 0x900
    int64_t v1; // 0x900
    __libc_start_main(2570, (int32_t)a4, (char **)&v1, (void (*)())2848, (void (*)())2960, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x930 - 0x962
int64_t deregister_tm_clones(void) {
    // 0x930
    return 0x201010;
}

// Address range: 0x970 - 0x9b2
int64_t register_tm_clones(void) {
    // 0x970
    return 0;
}

// Address range: 0x9c0 - 0x9fa
int64_t __do_global_dtors_aux(void) {
    // 0x9c0
    if (g6 != 0) {
        // 0x9f8
        int64_t result; // 0x9c0
        return result;
    }
    // 0x9c9
    if (g3 != 0) {
        // 0x9d7
        __cxa_finalize((int64_t *)*(int64_t *)0x201008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x9e3
    g6 = 1;
    return result2;
}

// Address range: 0xa00 - 0xa0a
int64_t frame_dummy(void) {
    // 0xa00
    return register_tm_clones();
}

// Address range: 0xa0a - 0xabf
int main(int argc, char ** argv) {
    // 0xa0a
    int64_t v1; // bp-8, 0xa0a
    int64_t v2 = (int64_t)&v1 - 80; // 0xa37
    int64_t v3 = 0;
    *(int32_t *)(v2 + 4 * v3) = (int32_t)v3;
    int64_t v4 = v3 + 1;
    int32_t v5 = 0; // 0xa2d
    while (v4 != 15) {
        // 0xa2f
        v3 = v4;
        *(int32_t *)(v2 + 4 * v3) = (int32_t)v3;
        v4 = v3 + 1;
        v5 = 0;
    }
    int64_t v6 = _ZNSolsEi((int32_t)&g5); // 0xa9e
    _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v6, (char *)2981);
    int32_t v7 = v5 + 1; // 0xab2
    v5 = v7;
    while (v7 != 15) {
        // 0xa8c
        v6 = _ZNSolsEi((int32_t)&g5);
        _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v6, (char *)2981);
        v7 = v5 + 1;
        v5 = v7;
    }
    // 0xab8
    return 0;
}

// Address range: 0xabf - 0xb08
// Demangled:     __static_initialization_and_destruction_0(int, int)
int64_t _Z41__static_initialization_and_destruction_0ii(int32_t a1, int32_t a2) {
    int64_t result; // 0xabf
    if (a1 == 1 == a2 == 0xffff) {
        // 0xadc
        _ZNSt8ios_base4InitC1Ev();
        int64_t v1 = *(int64_t *)0x200ff8; // 0xaf6
        int32_t v2 = __cxa_atexit((void (*)(int64_t *))v1, &g7, &g4); // 0xb00
        result = v2;
    }
    // 0xb05
    return result;
}

// Address range: 0xb08 - 0xb1d
int64_t _GLOBAL__sub_I_main(void) {
    // 0xb08
    return _Z41__static_initialization_and_destruction_0ii(1, 0xffff);
}

// Address range: 0xb20 - 0xb85
int64_t __libc_csu_init(int64_t a1, int64_t a2, int64_t a3) {
    int64_t result = _init(); // 0xb4c
    if ((int64_t)&g2 - (int64_t)&g1 >> 3 == 0) {
        // 0xb76
        return result;
    }
    int64_t v1 = 0; // 0xb54
    while (v1 + 1 != (int64_t)&g2 - (int64_t)&g1 >> 3) {
        // 0xb60
        v1++;
    }
    // 0xb76
    return result;
}

// Address range: 0xb90 - 0xb92
int64_t __libc_csu_fini(void) {
    // 0xb90
    int64_t result; // 0xb90
    return result;
}

// Address range: 0xb94 - 0xb9d
int64_t _fini(void) {
    // 0xb94
    int64_t result; // 0xb94
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int __cxa_atexit(void(* func)(void *), void * arg, void * dso_handle);
// void __cxa_finalize(void * d);
// void __gmon_start__(void);
// int __libc_start_main(int *(main)(int, char **, char **), int argc, char ** ubp_av, void(* init)(void), void(* fini)(void), void(* rtld_fini)(void), void(* stack_end));
// int64_t _ZNSolsEi(int32_t a1);
// int64_t _ZNSt8ios_base4InitC1Ev(void);
// int64_t _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(int64_t * a1, char * a2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.3.0)
// Detected functions: 17

